SERVER_IP_ADDRESS = '127.0.0.1'
MAX_CLIENT_IN_QUEUE = 5
RECV_LENGTH = 2048
SEND_LENGTH = 2048

SERVER_COMMANDS = {'USER': 2, 'PASS': 2, 'PWD': 1, 'MKD': [2, 3], 'RMD': [2, 3],
                   'LIST': 1, 'CWD': [1, 2], 'DL': 2, "HELP": 1, 'QUIT': 1}

CLIENT_READY_TO_RECEIVE_LIST = "ok"
CLIENT_AGREE_TO_DOWNLOAD_MSG = "OK"
CLIENT_DOWNLOAD_SUCCESSFULLY = "200"
CLIENT_DOWNLOAD_UNSUCCESSFUL = "500"
